### ISSUE TITLE
registry error

### ISSUE THREAD

**Issue by ujj** [ivirabyan/django-mentions#4]
Getting a registry error when I include 'mentions' in my INSTALLED_APPS in my Django 1.9 project. 

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10186cb70>
Traceback (most recent call last):
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/mentions/__init__.py", line 1, in <module>
    from .registry import Provider
  File "/Users/ujjwal/workspace/play/ph4/penv/lib/python3.5/site-packages/mentions/registry.py", line 69
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
```

**Comment by ivirabyan** [comment]
This application was not tested with recent versions of Django. It may fail, since app loading was refactored in Django. I'll try to make it compatible though.

**Comment by sebastianjungels** [comment]
was this fixed?
